name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      - name: Clean npm Cache
        run: npm cache clean --force
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        env:
          VITE_DOCUMENT_API_KEY: ${{ secrets.VITE_DOCUMENT_API_KEY }}
          VITE_KAKAO_API: ${{ secrets.VITE_KAKAO_API }}
        run: npm run build

      - name: Debug Build Files
        run: |
          ls
          echo "---------------------------------"
          cd dist
          ls

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Remove Existing Files from S3
        run: aws s3 rm s3://Frontend --recursive

      - name: Deploy New Build to S3
        run: aws s3 cp ./dist s3://Frontend/ --recursive

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id EQEIPG9IJRV5K --paths "/*"
